// recorder.rs — Post-call exact usage recording (Tier 1).
//
// After every LLM API call the provider returns exact token counts in its
// response body (e.g. `usage.input_tokens`, `usage.output_tokens` from
// Anthropic, or `usage.prompt_tokens`, `usage.completion_tokens` from OpenAI).
//
// `UsageRecord` models that provider-returned payload in a provider-agnostic
// way.  `TokenRecorder` accumulates records for a session and exposes aggregate
// statistics used by the budget and session-state subsystems.
//
// Design notes:
//   - Records are stored oldest-first (push order) so that
//     `history()` naturally returns a chronological view without
//     allocating a temporary vector or prepending elements (which is slower).
//   - All summation uses `saturating_add` — token counts are order-of-millions
//     at most; silent clamping at usize::MAX is correct behaviour for this domain.

use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// UsageRecord
// ---------------------------------------------------------------------------

/// A single turn's token usage as reported by the provider API.
///
/// This is Tier 1 — ground truth.  Every field that the provider sends should
/// be populated; optional fields cover provider-specific extensions (Anthropic
/// prompt caching).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsageRecord {
    /// Tokens in the prompt/input sent to the model this turn.
    /// This is the *full* context window size — system prompt + history +
    /// user message — which is what matters for window-limit management.
    pub input_tokens: usize,

    /// Tokens in the completion/output generated by the model this turn.
    pub output_tokens: usize,

    /// Anthropic prompt-caching: tokens read from the prompt cache (cheaper).
    /// `None` for providers that don't support prompt caching.
    pub cache_read_tokens: Option<usize>,

    /// Anthropic prompt-caching: tokens written into the prompt cache.
    /// `None` for providers that don't support prompt caching.
    pub cache_write_tokens: Option<usize>,

    /// The model identifier string as returned by the provider
    /// (e.g. `"claude-sonnet-4-5"`, `"gpt-4o"`).
    pub model: String,

    /// The provider name (e.g. `"anthropic"`, `"openai"`, `"deepseek"`).
    pub provider: String,
}

impl UsageRecord {
    /// Total tokens consumed this turn (input + output).
    ///
    /// Useful for per-turn cost estimation.  Uses `saturating_add` so a
    /// pathological response with absurd counts does not panic.
    pub fn total(&self) -> usize {
        self.input_tokens.saturating_add(self.output_tokens)
    }

    /// The number of input tokens that are billed at the standard rate.
    ///
    /// For providers without prompt caching this is identical to
    /// `input_tokens`.  For Anthropic, cached reads are billed at a fraction
    /// of the standard rate — but token *budget* logic still uses
    /// `input_tokens` (the full context size) rather than the billed amount,
    /// because the window limit is a hard technical constraint, not a cost one.
    pub fn billed_input(&self) -> usize {
        // The spec intentionally keeps this simple: return input_tokens.
        // If future cost-tracking needs arise, this is the right place to
        // subtract cache_read_tokens after applying the discount factor.
        self.input_tokens
    }
}

// ---------------------------------------------------------------------------
// TokenRecorder
// ---------------------------------------------------------------------------

/// Accumulates per-turn `UsageRecord`s for a session.
///
/// Records are stored in chronological order (oldest at index 0),
/// so `last()` and `history()` are O(1) reads without extra allocation.
#[derive(Debug, Clone)]
pub struct TokenRecorder {
    /// Internal storage, oldest-first (push order).
    records: Vec<UsageRecord>,
}

impl TokenRecorder {
    /// Create a new, empty recorder.
    pub fn new() -> Self {
        Self {
            records: Vec::new(),
        }
    }

    /// Append an exact-usage record from an API response.
    ///
    /// The record is pushed to the end of the vector to maintain oldest-first chronological ordering.
    /// Pushing is O(1) and extremely efficient.
    pub fn record(&mut self, usage: UsageRecord) {
        // Append to the vector. The newest record is always at the last position.
        self.records.push(usage);
    }

    /// Return the most recent `UsageRecord`, or `None` if no turns recorded yet.
    pub fn last(&self) -> Option<&UsageRecord> {
        // The last element in the vector is the newest because we push on record().
        self.records.last()
    }

    /// Sum of all recorded `input_tokens` across all turns this session.
    pub fn total_input(&self) -> usize {
        self.records
            .iter()
            .fold(0usize, |acc, r| acc.saturating_add(r.input_tokens))
    }

    /// Sum of all recorded `output_tokens` across all turns this session.
    pub fn total_output(&self) -> usize {
        self.records
            .iter()
            .fold(0usize, |acc, r| acc.saturating_add(r.output_tokens))
    }

    /// Grand total of all tokens (input + output) across all turns.
    pub fn total_tokens(&self) -> usize {
        self.total_input().saturating_add(self.total_output())
    }

    /// All recorded turns in chronological order (oldest first).
    ///
    /// The returned slice is a direct view into internal storage — zero-copy.
    pub fn history(&self) -> &[UsageRecord] {
        &self.records
    }

    /// Discard all recorded turns.  Useful when starting a new session or
    /// after a context compaction resets the conversation.
    pub fn clear(&mut self) {
        self.records.clear();
    }
}

impl Default for TokenRecorder {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// Build a `UsageRecord` with the given input/output counts and sane defaults
    /// for the other fields.  Keeps test code concise.
    fn make_record(input: usize, output: usize) -> UsageRecord {
        UsageRecord {
            input_tokens: input,
            output_tokens: output,
            cache_read_tokens: None,
            cache_write_tokens: None,
            model: "test-model".to_string(),
            provider: "test-provider".to_string(),
        }
    }

    // -----------------------------------------------------------------------
    // UsageRecord helpers
    // -----------------------------------------------------------------------

    #[test]
    fn usage_record_total_sums_input_and_output() {
        let r = make_record(1_000, 250);
        assert_eq!(r.total(), 1_250);
    }

    #[test]
    fn usage_record_billed_input_equals_input_tokens() {
        // Without caching, billed_input == input_tokens.
        let r = make_record(500, 100);
        assert_eq!(r.billed_input(), 500);
    }

    #[test]
    fn usage_record_total_saturates_on_overflow() {
        // Both fields at max should saturate, not panic.
        let r = make_record(usize::MAX, usize::MAX);
        assert_eq!(r.total(), usize::MAX);
    }

    #[test]
    fn usage_record_with_cache_fields_serialises() {
        let r = UsageRecord {
            input_tokens: 2_048,
            output_tokens: 512,
            cache_read_tokens: Some(1_024),
            cache_write_tokens: Some(256),
            model: "claude-sonnet-4-5".into(),
            provider: "anthropic".into(),
        };
        let json = serde_json::to_string(&r).expect("serialise");
        let back: UsageRecord = serde_json::from_str(&json).expect("deserialise");
        assert_eq!(back.cache_read_tokens, Some(1_024));
        assert_eq!(back.cache_write_tokens, Some(256));
    }

    // -----------------------------------------------------------------------
    // TokenRecorder
    // -----------------------------------------------------------------------

    #[test]
    fn new_recorder_is_empty() {
        let rec = TokenRecorder::new();
        assert!(rec.last().is_none());
        assert_eq!(rec.total_tokens(), 0);
        assert!(rec.history().is_empty());
    }

    #[test]
    fn record_single_turn_and_retrieve_last() {
        let mut rec = TokenRecorder::new();
        rec.record(make_record(1_024, 256));
        let last = rec.last().expect("should have a record");
        assert_eq!(last.input_tokens, 1_024);
        assert_eq!(last.output_tokens, 256);
    }

    #[test]
    fn total_tokens_sums_correctly_across_multiple_records() {
        // Real-world scenario: 3 turns of a conversation.
        let mut rec = TokenRecorder::new();
        rec.record(make_record(500, 100)); // turn 1
        rec.record(make_record(700, 200)); // turn 2
        rec.record(make_record(900, 300)); // turn 3

        assert_eq!(rec.total_input(), 500 + 700 + 900);
        assert_eq!(rec.total_output(), 100 + 200 + 300);
        assert_eq!(rec.total_tokens(), (500 + 700 + 900) + (100 + 200 + 300));
    }

    #[test]
    fn history_is_oldest_first() {
        // history()[0] must be the oldest recorded turn.
        let mut rec = TokenRecorder::new();
        rec.record(make_record(100, 10)); // oldest
        rec.record(make_record(200, 20)); // newest

        let h = rec.history();
        assert_eq!(h.len(), 2);
        assert_eq!(h[0].input_tokens, 100, "oldest should be at index 0");
        assert_eq!(h[1].input_tokens, 200, "newest should be at index 1");
    }

    #[test]
    fn last_returns_most_recent_record() {
        let mut rec = TokenRecorder::new();
        rec.record(make_record(100, 10));
        rec.record(make_record(999, 111)); // this should be "last"
        let last = rec.last().expect("should have records");
        assert_eq!(last.input_tokens, 999);
    }

    #[test]
    fn clear_empties_all_records() {
        let mut rec = TokenRecorder::new();
        rec.record(make_record(1_000, 200));
        rec.record(make_record(2_000, 400));
        rec.clear();

        assert!(rec.last().is_none());
        assert_eq!(rec.total_tokens(), 0);
        assert!(rec.history().is_empty());
    }

    #[test]
    fn default_impl_matches_new() {
        let a = TokenRecorder::new();
        let b = TokenRecorder::default();
        // Both should be empty.
        assert_eq!(a.total_tokens(), b.total_tokens());
        assert_eq!(a.history().len(), b.history().len());
    }
}
