//! Argument types for the edit tool.
//!
//! Hey friend! This module defines the resilient deserialization schema for the edit tool's input.
//! It is designed with defensive parsing to seamlessly handle open-weights model quirks,
//! including stringified JSON arrays, markdown-fenced arguments, field name aliases,
//! single-object hunk inputs, and flat top-level parameters.

use operon_tools_core::de::strip_markdown_fences;
use serde::{Deserialize, Deserializer, Serialize};

/// A single search-and-replace operation.
///
/// Each hunk specifies a string to find and its replacement.
/// Supports common field aliases generated by various LLM architectures.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EditHunk {
    /// Exact or unique text to find in the file.
    #[serde(
        alias = "old_str",
        alias = "old_text",
        alias = "oldText",
        alias = "oldString",
        alias = "search",
        alias = "find",
        alias = "pattern",
        alias = "old",
        alias = "original",
        alias = "target"
    )]
    pub old_string: String,

    /// Replacement text. Must differ from `old_string`.
    #[serde(
        alias = "new_str",
        alias = "new_text",
        alias = "newText",
        alias = "newString",
        alias = "replacement",
        alias = "replace",
        alias = "new",
        alias = "modified",
        alias = "update"
    )]
    pub new_string: String,
}

/// Helper to deserialize `edits` from multiple flexible shapes:
/// 1. Real JSON array: `[ EditHunk, ... ]`
/// 2. Stringified JSON array: `"[{\"old_string\": ...}]"`
/// 3. Markdown-fenced string: `"```json\n[...]\n```"`
/// 4. Single `EditHunk` object: `{"old_string": "...", "new_string": "..."}`
/// 5. Stringified single object: `"{\"old_string\": ...}"`
fn deserialize_flexible_edits<'de, D>(deserializer: D) -> Result<Vec<EditHunk>, D::Error>
where
    D: Deserializer<'de>,
{
    let value = serde_json::Value::deserialize(deserializer)?;
    parse_edits_from_value(&value).map_err(serde::de::Error::custom)
}

/// Parses a `serde_json::Value` into `Vec<EditHunk>`.
fn parse_edits_from_value(value: &serde_json::Value) -> Result<Vec<EditHunk>, String> {
    match value {
        serde_json::Value::Array(_) => {
            serde_json::from_value(value.clone()).map_err(|e| format!("invalid edits array: {e}"))
        }
        serde_json::Value::Object(_) => {
            // Single hunk passed as an object instead of array
            let hunk: EditHunk = serde_json::from_value(value.clone())
                .map_err(|e| format!("invalid edit object: {e}"))?;
            Ok(vec![hunk])
        }
        serde_json::Value::String(s) => {
            let cleaned = strip_markdown_fences(s);
            let inner_value: serde_json::Value = serde_json::from_str(cleaned)
                .map_err(|e| format!("failed to parse stringified edits JSON: {e}"))?;
            parse_edits_from_value(&inner_value)
        }
        serde_json::Value::Null => Ok(Vec::new()),
        other => Err(format!("unexpected edits format: {other}")),
    }
}

/// Raw representation used for deserialization of `EditArgs`.
#[derive(Debug, Deserialize)]
struct RawEditArgs {
    #[serde(
        alias = "file_path",
        alias = "filePath",
        alias = "filepath",
        alias = "target_file",
        alias = "targetFile",
        alias = "file",
        alias = "filename",
        alias = "fileName"
    )]
    pub path: Option<String>,

    #[serde(
        default,
        deserialize_with = "deserialize_flexible_edits",
        alias = "hunks",
        alias = "changes",
        alias = "replacements",
        alias = "operations",
        alias = "patches"
    )]
    pub edits: Vec<EditHunk>,

    // Flat top-level single edit aliases
    #[serde(
        default,
        alias = "old_str",
        alias = "old_text",
        alias = "oldText",
        alias = "oldString",
        alias = "search",
        alias = "find",
        alias = "pattern",
        alias = "old",
        alias = "original",
        alias = "target"
    )]
    pub old_string: Option<String>,

    #[serde(
        default,
        alias = "new_str",
        alias = "new_text",
        alias = "newText",
        alias = "newString",
        alias = "replacement",
        alias = "replace",
        alias = "new",
        alias = "modified",
        alias = "update"
    )]
    pub new_string: Option<String>,
}

/// Arguments for the edit tool.
///
/// Specifies a target file path and one or more edits to apply.
#[derive(Debug, Clone, Serialize)]
pub struct EditArgs {
    /// Absolute path to the file to edit.
    pub path: String,

    /// One or more edits to apply in order.
    pub edits: Vec<EditHunk>,
}

impl<'de> Deserialize<'de> for EditArgs {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let raw = RawEditArgs::deserialize(deserializer)?;

        let path = raw.path.ok_or_else(|| {
            serde::de::Error::missing_field("path")
        })?;

        let mut edits = raw.edits;

        // Fallback: If `edits` is empty but flat `old_string` & `new_string` were provided at root level
        if edits.is_empty() {
            if let (Some(old_str), Some(new_str)) = (raw.old_string, raw.new_string) {
                edits.push(EditHunk {
                    old_string: old_str,
                    new_string: new_str,
                });
            }
        }

        Ok(EditArgs { path, edits })
    }
}
