'use strict';

/**
 * settings-panel.js
 *
 * Core orchestrator for the Settings popup dialog.
 *
 * Responsibilities:
 *  1. Build and inject the dialog HTML into the document.
 *  2. Open / close the dialog (only via the close button — not backdrop click).
 *  3. Track and switch between settings categories.
 *  4. Delegate page rendering and hydration to each category's JS module.
 *  5. Export shared utility helpers (buildSettingRow, escapeHtml, etc.)
 *     that category modules depend on.
 *
 * Dialog structure:
 *  .settings-overlay          <- full-screen backdrop
 *    .settings-dialog         <- 70vw × 70vh centered card
 *      .settings-dialog__header
 *        h2.settings-dialog__title
 *        button.settings-dialog__close
 *      .settings-dialog__body
 *        nav.settings-dialog__sidebar   <- left navigation
 *        main.settings-dialog__main     <- category page content
 */

import { buildLeftSidebar, highlightNavItem } from './left-sidebar.js';
import { buildGeneralPage, saveSettings as saveGeneralSettings } from './settings-main-content/general.js';
import { buildAppearancePage, hydrateAppearancePage, applyAppearanceSettings, resetAppearanceSettingsState } from './settings-main-content/appearance.js';
import { resetModelsSettingsState, hydrateModelsPage } from './settings-main-content/models.js';
import { resetChannelsSettingsState, hydrateChannelsPage } from './settings-main-content/channels.js';
import { resetPermissionsSettingsState, hydratePermissionsPage } from './settings-main-content/permissions.js';
import { resetSkillsSettingsState, hydrateSkillsPage } from './settings-main-content/skills.js';
import { resetExtensionsSettingsState, hydrateExtensionsPage } from './settings-main-content/extensions.js';
import { buildAboutPageContent, hydrateAboutPage } from './settings-main-content/about.js';

// ── Module-Level State ───────────────────────────────────────────────────────

/**
 * The currently active settings category key.
 * Exported so that category modules can guard against stale renders
 * (e.g., "only render if activeCategory === 'models'").
 * @type {string}
 */
let activeCategory = 'models';

/**
 * Whether the settings dialog is currently open.
 * @type {boolean}
 */
let isOpen = false;

// ── Category Definitions ─────────────────────────────────────────────────────

// Each category key is mapped to its label and corresponding SVG filename located
// in the correct settings icons directory (gui/src/assets/icons/settings/).
const CATEGORIES = [
  { key: 'general',     label: 'General',     icon: 'category-general.svg' },
  { key: 'appearance',  label: 'Appearance',  icon: 'category-appearance.svg'    },
  { key: 'models',      label: 'Models',      icon: 'category-models.svg'      },
  { key: 'channels',    label: 'Channels',    icon: 'category-channels.svg'       },
  { key: 'permissions', label: 'Permissions', icon: 'category-permissions.svg'     },
  { key: 'skills',      label: 'Skills',      icon: 'category-skills.svg'     },
  { key: 'extensions',  label: 'Extensions',  icon: 'category-extensions.svg'        },
  { key: 'about',       label: 'About',       icon: 'category-about.svg'},
];

// ── DOM References ───────────────────────────────────────────────────────────

/** @type {HTMLElement|null} */
let overlayEl = null;

/** @type {HTMLElement|null} */
let mainEl = null;

// ── Initialization ───────────────────────────────────────────────────────────

/**
 * Creates the settings dialog element and appends it to <body>.
 * Should be called ONCE at application startup before openSettings().
 */
function initSettingsPanel() {
  // Guard: don't create a second overlay if already initialized
  if (document.getElementById('settings-overlay')) {
    return;
  }

  // Build the complete dialog HTML
  const overlayHtml = buildDialogHtml();

  // Inject into the end of <body>
  document.body.insertAdjacentHTML('beforeend', overlayHtml);

  // Cache DOM references
  overlayEl = document.getElementById('settings-overlay');
  mainEl = document.getElementById('settings-main');

  // Wire up the close button — ONLY the X button closes the dialog
  const closeBtn = document.getElementById('settings-close-btn');
  if (closeBtn) {
    closeBtn.addEventListener('click', closeSettings);
  }

  // Bind sidebar category click delegation
  const sidebar = document.getElementById('settings-sidebar');
  if (sidebar) {
    sidebar.addEventListener('click', handleSidebarClick);
  }

  // Apply saved appearance settings on startup
  applyAppearanceSettings();
}

// ── Dialog HTML Builder ──────────────────────────────────────────────────────

/**
 * Returns the complete HTML string for the settings overlay + dialog.
 * The sidebar nav is generated by buildLeftSidebar().
 * @returns {string}
 */
function buildDialogHtml() {
  return `
    <div class="settings-overlay" id="settings-overlay" role="dialog" aria-modal="true" aria-labelledby="settings-dialog-title">
      <div class="settings-dialog" id="settings-dialog">

        <!-- ── Header row (title + close button) ── -->
        <div class="settings-dialog__header">
          <h2 class="settings-dialog__title" id="settings-dialog-title">Settings</h2>
          <button
            class="settings-dialog__close"
            id="settings-close-btn"
            type="button"
            aria-label="Close settings"
            title="Close">
            ${buildCloseIconSvg()}
          </button>
        </div>

        <!-- ── Body (sidebar + main content) ── -->
        <div class="settings-dialog__body">

          <!-- Left navigation sidebar -->
          <nav class="settings-dialog__sidebar" id="settings-sidebar" aria-label="Settings categories">
            ${buildLeftSidebar(CATEGORIES, activeCategory)}
          </nav>

          <!-- Main content area — filled by renderCategoryPage() -->
          <main class="settings-dialog__main" id="settings-main" aria-live="polite">
          </main>

        </div>
      </div>
    </div>
  `;
}

/**
 * Returns an img tag pointing to the close (X) icon file.
 * The correct filename is close.svg and we load it relative to the index.html file
 * using './assets/icons/settings/close.svg'.
 * @returns {string}
 */
function buildCloseIconSvg() {
  return `<img src="./assets/icons/settings/close.svg" alt="Close" width="16" height="16" draggable="false">`;
}

// ── Open / Close ─────────────────────────────────────────────────────────────

/**
 * Opens the settings dialog.
 * Renders the last active category (or 'general' on first open).
 * @param {string} [category='general'] - Optional: jump directly to a category.
 */
function openSettings(category = activeCategory) {
  const disabledCategories = ['general', 'appearance', 'channels', 'skills', 'extensions', 'about'];
  if (disabledCategories.includes(category)) {
    category = 'models';
  }
  if (isOpen) {
    // If already open, just switch category if needed
    if (category !== activeCategory) {
      switchCategory(category);
    }
    return;
  }

  if (!overlayEl) {
    // Panel was never initialized — init now as a fallback
    initSettingsPanel();
  }

  isOpen = true;
  overlayEl.classList.add('is-open');

  // Lock body scroll while dialog is open
  document.body.style.overflow = 'hidden';

  // Render the current category
  switchCategory(category);
}

/**
 * Closes the settings dialog.
 * Resets transient async states in all category modules.
 */
function closeSettings() {
  if (!isOpen) return;

  isOpen = false;
  overlayEl.classList.remove('is-open');

  // Restore body scroll
  document.body.style.overflow = '';

  // Reset all transient loading/saving states so that re-opening
  // starts with a clean slate rather than stale spinners.
  resetAllCategoryStates();
}

/**
 * Resets transient module-level state across all category modules.
 * Called on dialog close.
 */
function resetAllCategoryStates() {
  resetAppearanceSettingsState();
  resetModelsSettingsState();
  resetChannelsSettingsState();
  resetPermissionsSettingsState();
  resetSkillsSettingsState();
  resetExtensionsSettingsState();
}

// ── Category Switching ───────────────────────────────────────────────────────

/**
 * Switches the main content area to the specified category.
 * Updates sidebar active highlight and re-renders the page.
 * @param {string} key - Category key (e.g. 'general', 'models').
 */
function switchCategory(key) {
  // Normalize the key — fall back to 'models' if unknown
  const resolved = CATEGORIES.find(c => c.key === key) ? key : 'models';
  activeCategory = resolved;

  // Update nav highlight
  const sidebar = document.getElementById('settings-sidebar');
  if (sidebar) {
    highlightNavItem(sidebar, resolved);
  }

  // Render the page for this category
  renderCategoryPage(resolved);
}

/**
 * Renders and hydrates the appropriate page into the main content area.
 * @param {string} category - Category key.
 */
async function renderCategoryPage(category) {
  if (!mainEl) return;

  // PLACEHOLDER: Default settings values for UI
  const settings = {
    launchAtStartup: false,
    enterBehavior: 'send',
    autoScroll: true,
    codeWrap: false,
    language: 'en',
  };

  // 1. Build static HTML for the page
  let html = '';
  switch (category) {
    case 'general':
      html = buildGeneralPage(settings);
      break;
    case 'appearance':
      html = buildAppearancePage(settings);
      break;
    case 'models':
      html = buildModelsPage();
      break;
    case 'channels':
      html = buildChannelsPage();
      break;
    case 'permissions':
      html = buildPermissionsPage();
      break;
    case 'skills':
      html = buildSkillsPage();
      break;
    case 'extensions':
      html = buildExtensionsPage();
      break;
    case 'about':
      html = buildAboutPageContent();
      break;
    default:
      html = buildGeneralPage(settings, state);
  }

  // 2. Inject HTML
  mainEl.innerHTML = html;

  // 3. Hydrate (bind events, trigger async data fetches)
  const dialog = document.getElementById('settings-dialog');
  switch (category) {
    case 'appearance':
      hydrateAppearancePage(mainEl);
      break;
    case 'models':
      await hydrateModelsPage(dialog);
      break;
    case 'channels':
      await hydrateChannelsPage(dialog);
      break;
    case 'permissions':
      await hydratePermissionsPage(dialog);
      break;
    case 'skills':
      await hydrateSkillsPage(dialog);
      break;
    case 'extensions':
      await hydrateExtensionsPage(dialog);
      break;
    case 'about':
      await hydrateAboutPage(mainEl);
      break;
    default:
      // general page needs no special hydration
      break;
  }

  // 4. Bind general-page save button if on general category
  if (category === 'general') {
    const saveBtn = mainEl.querySelector('#btn-check-updates');
    if (saveBtn) {
      saveBtn.addEventListener('click', () => {
        // Placeholder: trigger update check through IPC when available
        saveGeneralSettings();
      });
    }
  }
}

// ── Sidebar Delegation ───────────────────────────────────────────────────────

/**
 * Handles clicks inside the sidebar nav via event delegation.
 * Reads the data-category attribute from the clicked nav item.
 * @param {MouseEvent} event
 */
function handleSidebarClick(event) {
  const btn = /** @type {HTMLElement} */ (event.target).closest('[data-settings-category]');
  if (!btn) return;

  const key = btn.getAttribute('data-settings-category');
  if (key === 'general') {
    alert('General settings coming soon!');
    return;
  }
  if (key === 'appearance') {
    alert('Appearance settings coming soon!');
    return;
  }
  if (key === 'channels') {
    alert('Channels settings coming soon!');
    return;
  }
  if (key === 'skills') {
    alert('Skills settings coming soon!');
    return;
  }
  if (key === 'extensions') {
    alert('Extensions settings coming soon!');
    return;
  }
  if (key === 'about') {
    alert('About settings coming soon!');
    return;
  }
  if (key && key !== activeCategory) {
    switchCategory(key);
  }
}

// ── Static Page Stubs ────────────────────────────────────────────────────────
// Pages with dynamic async content return a minimal host scaffold that the
// module's hydrate function then fills via renderXxxStage(modal).

/**
 * Returns the host scaffold HTML for the Models page.
 * @returns {string}
 */
function buildModelsPage() {
  return `
    <div class="settings-page">
      <h2 class="settings-page__title" data-models-title>Models</h2>
      <p class="settings-page__description" data-models-description>
        Configure model providers, credentials, and active model selection
      </p>
      <!-- Async content injected by hydrateModelsPage() -->
      <div data-models-host></div>
    </div>
  `;
}

/**
 * Returns the host scaffold HTML for the Channels page.
 * @returns {string}
 */
function buildChannelsPage() {
  return `
    <div class="settings-page">
      <h2 class="settings-page__title">Channels</h2>
      <p class="settings-page__description" data-channels-description>
        Configure messaging connectors for Telegram, Discord, WhatsApp, and Email
      </p>
      <!-- Async content injected by hydrateChannelsPage() -->
      <div data-channels-host></div>
    </div>
  `;
}

/**
 * Returns the host scaffold HTML for the Permissions page.
 * @returns {string}
 */
function buildPermissionsPage() {
  return `
    <div class="settings-page">
      <h2 class="settings-page__title">Permissions</h2>
      <p class="settings-page__description">
        Control which directories and tools the agent can access
      </p>
      <!-- Async content injected by hydratePermissionsPage() -->
      <div data-permissions-host></div>
    </div>
  `;
}

/**
 * Returns the host scaffold HTML for the Skills page.
 * @returns {string}
 */
function buildSkillsPage() {
  return `
    <div class="settings-page">
      <h2 class="settings-page__title">Skills</h2>
      <p class="settings-page__description">
        Browse and install reusable skills from the OHub registry
      </p>
      <!-- Async content injected by hydrateSkillsPage() -->
      <div data-skills-host></div>
    </div>
  `;
}

/**
 * Returns the host scaffold HTML for the Extensions page.
 * @returns {string}
 */
function buildExtensionsPage() {
  return `
    <div class="settings-page">
      <h2 class="settings-page__title">Extensions</h2>
      <p class="settings-page__description">
        Browse, download, and manage runtime extensions
      </p>
      <!-- Async content injected by hydrateExtensionsPage() -->
      <div data-extensions-host></div>
    </div>
  `;
}

// ── Shared Utility Functions ──────────────────────────────────────────────────
// Exported for use by category-specific modules.

/**
 * Builds a generic two-column settings row.
 *
 * @param {string} label       - Left-side label text.
 * @param {string} description - Left-side description text (may be empty).
 * @param {string} controlHtml - Right-side control HTML (button, select, toggle, etc.).
 * @returns {string} HTML for the row.
 */
function buildSettingRow(label, description, controlHtml) {
  return `
    <div class="settings-row">
      <div class="settings-row__info">
        <div class="settings-row__label">${escapeHtml(label)}</div>
        ${description ? `<div class="settings-row__description">${escapeHtml(description)}</div>` : ''}
      </div>
      <div class="settings-row__control">
        ${controlHtml}
      </div>
    </div>
  `;
}

/**
 * Builds the "About" section used at the bottom of the General page.
 * @returns {string} HTML.
 */
function buildAboutSection() {
  return `
    <div class="settings-about">
      <div class="settings-about__logo">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24"
             fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
          <circle cx="12" cy="12" r="10"/>
          <path d="M12 8v4l3 3"/>
        </svg>
      </div>
      <div class="settings-about__info">
        <div class="settings-about__name">Operon</div>
        <div class="settings-about__version">Version 0.1.0</div>
      </div>
      <div class="settings-about__links">
        <a href="#" target="_blank" rel="noopener">GitHub</a>
        <span class="settings-about__divider">|</span>
        <a href="#" target="_blank" rel="noopener">Documentation</a>
        <span class="settings-about__divider">|</span>
        <a href="#" target="_blank" rel="noopener">Report Issue</a>
      </div>
    </div>
  `;
}

/**
 * Renders an inline status indicator (used for loading or empty states).
 *
 * @param {string}  message  - Human-readable status text.
 * @param {boolean} [loading=false] - If true, shows an animated spinner.
 * @returns {string} HTML.
 */
function renderInlineStatus(message, loading = false) {
  const spinner = loading
    ? `<span class="model-selector__spinner" aria-hidden="true"></span>`
    : '';
  return `
    <div class="settings-inline-status">
      ${spinner}
      <span>${escapeHtml(message)}</span>
    </div>
  `;
}

/**
 * Escapes HTML special characters to prevent XSS when interpolating
 * untrusted strings into template literals.
 *
 * @param {string} raw - Untrusted input.
 * @returns {string} HTML-safe string.
 */
function escapeHtml(raw) {
  return String(raw ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/**
 * Escapes a value for use inside an HTML attribute (e.g. data-*).
 * Replaces double-quotes so the attribute string remains valid.
 *
 * @param {string} raw - Input string.
 * @returns {string} Attribute-safe string.
 */
function escapeAttribute(raw) {
  return String(raw ?? '').replace(/"/g, '&quot;');
}

/**
 * Extracts a clean error message from an Error object, string, or unknown value.
 * Falls back to `fallback` when the error provides no useful message.
 *
 * @param {unknown} error    - Caught error of any type.
 * @param {string}  fallback - Shown when error.message is empty.
 * @returns {string}
 */
function normalizeErrorMessage(error, fallback = 'An unexpected error occurred.') {
  if (error instanceof Error && error.message) {
    return error.message;
  }
  if (typeof error === 'string' && error.trim()) {
    return error.trim();
  }
  return fallback;
}

// ── Exports ───────────────────────────────────────────────────────────────────

export {
  // Lifecycle
  initSettingsPanel,
  openSettings,
  closeSettings,

  // Shared state (read-only reference — do not mutate from outside)
  activeCategory,

  // Shared utilities used by category modules
  buildSettingRow,
  buildAboutSection,
  renderInlineStatus,
  escapeHtml,
  escapeAttribute,
  normalizeErrorMessage,

  // Category list (useful for testing or external nav)
  CATEGORIES,
};
