[package]
name        = "operon-tools-shell"
description = "All Operon agent shell tools. Organized into sub-crates: bash, etc."
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
repository.workspace = true

[dependencies]
operon-tools-core.workspace              = true
operon-tools-shell-bash.workspace        = true
operon-context-normalize-tools.workspace = true
serde_json.workspace                     = true
tokio.workspace                          = true

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["full"] }
