import { Tokens } from "../../shared/tokens.slint";

export component MarkdownParagraph inherits Text {
    in property <string> font-family-custom: Tokens.serif-font-family;
    in property <length> font-size-custom: Tokens.body-font-size;
    
    text: "";
    color: Tokens.text-primary;
    font-size: root.font-size-custom;
    font-family: root.font-family-custom;
    wrap: word-wrap;
    vertical-alignment: top;
    horizontal-alignment: left;
}
