// Action enum
// Represents all possible user intents in the TUI
// Key events are mapped to Actions in events/key.rs
// Actions are processed in main.rs event loop to update AppState

use crate::state::screen::ActiveScreen;
use crate::ui::chrome::right_sidebar::panel_state::RightPanelContent;
use std::path::PathBuf;

/// All possible actions that can occur in the TUI
/// Actions are generated by the event handler in response to:
/// - Keyboard input (mapped in events/key.rs)
/// - Timer ticks (for animations)
/// - Future: IPC messages from operon-rs backend
#[derive(Debug, Clone)]
pub enum Action {
    /// Exit the application
    Quit,
    
    /// Navigate to a different screen
    #[allow(dead_code)]
    Navigate(ActiveScreen),
    
    /// Go back to previous screen (eventually Chat)
    Back,
    
    /// Send the current message to the agent
    SendMessage,
    
    /// Open a file in the right panel preview
    #[allow(dead_code)]
    OpenFile(PathBuf),
    
    /// Show specific content in the right panel
    #[allow(dead_code)]
    ToggleRightPanel(RightPanelContent),
    
    /// Hide the right panel
    #[allow(dead_code)]
    CloseRightPanel,
    
    /// Toggle terminal panel (open if closed, close if open)
    ToggleTerminal,
    
    /// Open screen selector popup
    #[allow(dead_code)]
    OpenScreenSelector,
    
    /// Close screen selector popup
    CloseScreenSelector,
    
    /// Move selection up in screen selector
    ScreenSelectorUp,
    
    /// Move selection down in screen selector
    ScreenSelectorDown,
    
    /// Confirm screen selector selection
    ScreenSelectorConfirm,
    
    /// Input a character into the message box
    InputChar(char),
    
    /// Delete character before cursor (backspace)
    InputBackspace,
    
    /// Delete character at cursor (delete key)
    InputDelete,
    
    /// Insert newline in message box
    InputNewline,
    
    /// Move cursor left
    InputCursorLeft,
    
    /// Move cursor right
    InputCursorRight,
    
    /// Move cursor up
    InputCursorUp,
    
    /// Move cursor down
    InputCursorDown,
    
    /// Move cursor to start of input
    InputCursorHome,
    
    /// Move cursor to end of input
    InputCursorEnd,
    
    /// Process a raw key event (with full state context)
    ProcessKey(crossterm::event::KeyEvent),
    
    /// Process a mouse event
    ProcessMouse(crossterm::event::MouseEvent),
    
    /// Ctrl+Shift key state changed (for selection mode)
    #[allow(dead_code)]
    SetCtrlShiftHeld(bool),
    
    /// Copy selected text to clipboard
    #[allow(dead_code)]
    CopySelection,
    
    /// Scroll chat up
    #[allow(dead_code)]
    ScrollChatUp(u16),
    
    /// Scroll chat down
    #[allow(dead_code)]
    ScrollChatDown(u16),
    
    /// Agent response received
    AgentResponse(String),
    
    /// Periodic tick for animations (spinner, etc.)
    /// Sent by EventHandler at regular intervals
    Tick,
}
